### ISSUE TITLE
Ensure that GPAD (2.0) can be used as a primary input into the pipeline

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1443]
As we move forward, with the active Noctua imports being the deadline, the pipeline needs to be able to process GPAD 2.0 as a primary input component (GAF being the only other primary data component at this time).

Tied to this, to actually make use of GPAD elsewhere in the pipeline (e.g. produce GAF for AmiGO to consume), we'll also need to be making use of GPI 2.0 files.

Tagging @dougli1sqrd

**Comment by dougli1sqrd** [comment]
Datasets Yaml proposal:
GPAD datasets should have a new field `gpi` that is a list of dataset IDs within the group that refers to GPI files that are required for download and processing along with the gpad:
```
id: foo.gpad
dataset: foo
gpi:
  - foo.gpi
```

One question though that I have is which datasets are we considering to by the "correct" canonical datasets for a group? Now that we are expecting multiple types of files (gaf or gpad) we need a way of deciding which one is more canonical. 

For example, in the `goa.yaml` group, we have 3 entries that have `dataset: goa_chicken`: `goa_chicken.gaf`, `goa_chicken.gpad`, `goa_chicken.gpi`. This essentially represents 2 actual sources, as gpad+gpi is one, and then gaf. So even if we linked gpad to it's gpi, we still have to know which to use as the canonical.

We could just go totally one to one: where the goa_chicken.gaf gets processed to our canonical goa_chicken.gaf, the goa_chicken.gpad/gpi gets processed into our goa_chicken.gpad/gpi. To contrast, our current process takes GAF, and then produces all types from the one file. So we have a one to many.

We could also indicate in the yaml file which datasets are the blessed ones to use. Like:
```
# In goa.yaml
id: goa
sources:
  - goa_chicken.gpad
  - goa_chicken_isoform.gpad
  - goa_human.gpad
  - goa_cow.gaf
  ...
datasets:
  - id: goa_chicken.gpad
    gpi: [goa_chicken.gpi]
```

This allows the providers to say that *this* gaf source should be used, while *that* gpad source should be used.

Or perhaps there should be a flag in the datasets stanzas?

Ultimately, we need a way to map to our outputs. And having 3 sources that have `dataset: foo` in a file is unclear what to use. What do we think?

**Comment by kltm** [comment]
GPI can be there wither way, it's whether the GAF or GPAD(+GPI) should be the "primary" data source, assuming they aren't both different things. The assumption should be that unless otherwise marked, all data is processed through the pipeline. I would either comment out or add a tag for "inactive" (don't we have this) to track things that should not be processed normally.

**Comment by dougli1sqrd** [comment]
Yeah, we have a key for `active` I think. Currently we ignore it, but we could start. So in our goa_human case, since there's one for gaf and one for gpad+gpi, one of them must be inactive (or gone completely). 

Yeah, if we could devise a schema that detected this, that would be lovely. Otherwise we'll need validation logic. If ontobio detects that there are more than one source type for a `dataset`, then we'll be unable to proceed and we'll exit with an error I suppose.

**Comment by kltm** [comment]
Is the issue that there is a single identifier for a dataset so the collide? Either way, even if it cannot be encoded in a schema checker, it can be enforced, see https://github.com/geneontology/go-site/blob/master/scripts/sanity-check-users-and-groups.py

**Comment by dougli1sqrd** [comment]
Essentially yes. The `dataset` key is the name of upstream source independent of type. So goa_human.gaf has a dataset name of `goa_human`. It's what we use in ontobio to determine paths, file names, etc. And it's what we use when grabbing the download url for a type for a dataset. We ask for `dataset`s named X, of `type` Y, which will filter the list to one. The `id` field contains the `.gaf`, etc extension which is messier when determining file names, etc.

As for enforcing scripts, perfect!

**Comment by kltm** [comment]
I would propose then that this is an issue of policy:

* there should be one formatted file per dataset
  * if we *need* to track others (no evidence of this yet), they can be added as "inactive" and ignored by the pipeline
  * a script in travis will enforce the one-source-per-identifier rule

**Comment by pgaudet** [comment]
Do we have cases where there is more than one file ?

**Comment by kltm** [comment]
Yes, which is what started this thread--see @dougli1sqrd 's example at the top.

**Comment by dougli1sqrd** [comment]
```
 -
   id: goa_chicken.gpad
   label: "goa_chicken gpad file"
   description: "gpad file for goa_chicken from EBI Gene Ontology Annotation Database"
   url: http://current.geneontology.org/annotations/goa_chicken.gpad.gz
   type: gpad
   gpi: [ goa_chicken.gpi ]
   dataset: goa_chicken
   submitter: goa
   compression: gzip
   source: ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/CHICKEN/goa_chicken.gpa.gz
   entity_type: protein
   status: active
   species_code: Ggal
   taxa:
    - NCBITaxon:208524
```
