### ISSUE TITLE
Change type of Interpro in dbxrefs.yaml to be protein family, not polypeptide region

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#1874]
Current entry:

```yaml
- database: InterPro
  name: InterPro database of protein domains and motifs
  rdf_uri_prefix: https://registry.identifiers.org/registry/interpro
  synonyms:
    - INTERPRO
    - IPR
  generic_urls:
    - http://www.ebi.ac.uk/interpro/
  entity_types:
    - type_name: polypeptide region
      type_id: SO:0000839
      id_syntax: IPR\d{6}
      url_syntax: http://www.ebi.ac.uk/interpro/entry/[example_id]
      example_id: InterPro:IPR000001
      example_url: http://www.ebi.ac.uk/interpro/entry/IPR015421
```

This seems to be have the same entity type as PANTHER if it's to be used is combination with evidence codes that accept protein family

There is an issue for better documenting this:

- #1873
