### ISSUE TITLE
MEROPS entries are classified as proteins, but this isn't true for all MEROPS entries

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#1875]
Current entry:

```yaml
- database: MEROPS
  name: MEROPS peptidase database
  generic_urls:
    - https://www.ebi.ac.uk/merops/
  entity_types:
    - type_name: protein
      type_id: PR:000000001
      url_syntax: https://www.ebi.ac.uk/merops/cgi-bin/pepsum?id=[example_id]
      example_id: MEROPS:A08.001
      example_url: https://www.ebi.ac.uk/merops/cgi-bin/pepsum?id=A08.001
```

This is currently causing problems for groups that want to use MEROPS in conjunction with IKR, as IKR is restricted to families.

There is an issue for better documenting this:

- #1873

I also made a separate issue in bioregistry for MEROPs, it seems we are all treating MEROPS different and incorrectly in different ways: 

- https://github.com/biopragmatics/bioregistry/issues/439
