### ISSUE TITLE
db-xrefs.yaml appears to have an incorrect or improperly populated entry for PAINT_REF

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#236]
The current entry for PAINT_REF in db-xrefs.yaml is:
```yaml
- database: PAINT_REF
  name: Phylogenetic Annotation INference Tool References
  generic_urls:
    - http://www.pantherdb.org/
  entity_types:
    - type_name: entity
      type_id: BET:0000000
      url_syntax: http://www.geneontology.org/gene-associations/submission/paint/[example_id]/[example_id].txt
      example_id: PAINT_REF:PTHR10046
      example_url: http://www.geneontology.org/gene-associations/submission/paint/PTHR10046/PTHR10046.txt
```
The example URL there resolves just fine, but pulling one from AmiGO, e.g. http://www.geneontology.org/gene-associations/submission/paint/10909/10909.txt , resolves to nothing.

It seems clear that the error is getting in via the local part of the ID: PTHR10046 vs. 10046 ("PTHR" missing). The question is then: has this always been broken, or has bad data gotten into the system after a recent load? While this could be "fixed" at the db-xrefs.yaml level, it might be a bit awkward as the local part does seem to want to contain "PTHR". (Also, I'm assuming that the db-xres.yaml file is not otherwise wrong.)

I can confirm that "PAINT_REF:10909" is what AmiGO has in the index. This pushes the issue to the loader (always been broken) or the data (new problem).

@cmungall @selewis Any thoughts or recent changes here before I go into the loader? I don't have much truck (well, any) with the PANTHER data these days, but I remember there was some talk of changes there.

Initially spotted by @monicacecilia .
