### ISSUE TITLE
Remove GDB entry for db-xrefs.yaml

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#619]
Didn't GDB die in the 90s?

Certainly not active now, and the URL redirect goes to what may be a dodgy site

Mark as obsolete and remove all URLs

**Comment by pgaudet** [comment]
And remove all annotations ?

**Comment by cmungall** [comment]
Oh, I have to admit, I didn't bother to look, yeh looks like there are 29 annotations.

OK, we can at least remove this section:

```
  entity_types:
    - type_name: entity
      type_id: BET:0000000
      url_syntax: http://www.gdb.org/gdb-bin/genera/accno?accessionNum=GDB:[example_id]
      example_id: GDB:306600
      example_url: http://www.gdb.org/gdb-bin/genera/accno?accessionNum=GDB:306600
```

since AFAICT we have no annotations to GDB IDs, all adopted by UniProtKB.

We should retain GDB as provenance on these 29

And maybe we can change

```
  generic_urls:
    - http://www.gdb.org/
```

to post to the internet archive or a PMID?
