### ISSUE TITLE
Links to TAIR locus pages are wrong in AmiGO

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#659]
_From @tberardini on May 23, 2018 15:10_

Example:

http://amigo.geneontology.org/amigo/gene_product/TAIR:locus:2007651

The link URL to TAIR generated by AmiGO for locus:2007651 is

http://arabidopsis.org/servlets/TairObject?type=communication&id=locus:2007651

But should be:

https://www.arabidopsis.org/servlets/TairObject?accession=locus:2007651

Please fix.  Thank you.

_Copied from original issue: geneontology/amigo#503_

**Comment by kltm** [comment]
This likely traces back to https://github.com/geneontology/go-site/pull/443

**Comment by kltm** [comment]
@cmungall This seems similar to what we went through with WB a couple of months ago. This is essentially a collision being expressed in the "linker" code as it uses the main namespace as the lookup and TAIR has two different possible target for the same namespace.
See https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml#L2892
As, I believe, is mentioned in the analogus  WB tickets from April, full regexp lookup for all links would be quite expensive and we went with suggesting either splitting the namespace and/or having the receiving resource deal with the local id part. Experimenting with TAIR, the latter does not seem to be in place.

**Comment by kltm** [comment]
Also note: https://github.com/geneontology/go-site/pull/158

**Comment by tberardini** [comment]
Anything I can do to help resolve this?

**Comment by cmungall** [comment]
sorry can't give full attention now, can we just have the gene link be the default for now? This is 99.9% of the links clicked on I would wager

**Comment by kltm** [comment]
Will do.

**Comment by kltm** [comment]
This "patch"/"hack" is now in place for TAIR.

**Comment by tberardini** [comment]
Thank you!

**Comment by kltm** [comment]
NP.

I just want to spell this out so when we pick up on this again we have a quick start.
So, for example, here is all of the TAIR-ish information in our metadata as of this moment:

```yaml
- database: AGI_LocusCode
  name: Arabidopsis Genome Initiative
  description: Comprises TAIR, TIGR and MIPS
  generic_urls:
    - http://www.arabidopsis.org
  entity_types:
    - type_name: gene
      type_id: SO:0000704
      id_syntax: A[Tt][MmCc0-5][Gg][0-9]{5}(\.[0-9]{1})?
      url_syntax: http://arabidopsis.org/servlets/TairObject?type=locus&name=[example_id]
      example_id: AGI_LocusCode:At2g17950
      example_url: http://arabidopsis.org/servlets/TairObject?type=locus&name=At2g17950
- database: AraCyc
  name: AraCyc metabolic pathway database for Arabidopsis thaliana
  generic_urls:
    - http://www.arabidopsis.org/biocyc/index.jsp
  entity_types:
    - type_name: entity
      type_id: BET:0000000
      url_syntax: http://www.arabidopsis.org:1555/ARA/NEW-IMAGE?type=NIL&object=[example_id]
      example_id: AraCyc:PWYQT-62
      example_url: http://www.arabidopsis.org:1555/ARA/NEW-IMAGE?type=NIL&object=PWYQT-62
- database: TAIR
  name: The Arabidopsis Information Resource
  rdf_uri_prefix: http://identifiers.org/tair.locus/
  generic_urls:
    - http://www.arabidopsis.org/
  entity_types:
    - type_name: gene
      type_id: SO:0000704
      id_syntax: gene:[0-9]{7,12}
      url_syntax: http://arabidopsis.org/servlets/TairObject?accession=[example_id]
      example_id: TAIR:gene:2062713
      example_url: http://arabidopsis.org/servlets/TairObject?accession=gene:2062713
    - type_name: communication
      type_id: BET:0000000
      id_syntax: Communication:[0-9]{7,12}
      url_syntax: http://arabidopsis.org/servlets/TairObject?type=communication&id=[example_id]
      example_id: TAIR:Communication:1345790
      example_url: http://arabidopsis.org/servlets/TairObject?type=communication&id=1345790
    - type_name: primary transcript
      type_id: SO:0000185
      id_syntax: locus:[0-9]{7}
      url_syntax: http://arabidopsis.org/servlets/TairObject?accession=[example_id]
      example_id: TAIR:locus:2146653
      example_url: http://arabidopsis.org/servlets/TairObject?accession=locus:2146653
```

That's four URL schemes under three namespaces. Ideally, what we'd want is one of two things, which practically boils down to one thing done two different ways: a one namespace per URL scheme.

1) Split the TAIR communications into their own namespace (e.g. TAIR_COMM), like PAINT_REF, etc.
2) Setup a TAIR endpoint to resolve local IDs such that all entity types here have the same URL scheme (e.g. http://arabidopsis.org/servlets/TairObject?accession=ANYTHING:LOCAL_WHATEVS).

Really, for what we're doing, a better metadata format would have be to have the `url_syntax` stuff be at a higher level than under `entity_types` so that there was no confusing repetition for something we expect to be the same in practice.
