### ISSUE TITLE
JCVI URLs no longer resolve

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#923]
I'd like to follow up on GAF lines like:

```
JCVI_CMR    PSPTO_4722      PSPTO_4722              GO:0052078      PMID:12828636   IDA             P       type III effector HopAO1        hopAO1  protein taxon:223283|taxon:4100      20090612        PAMGO   
```

this is what we have:

```
- database: JCVI_CMR
  name: EGAD database at the J. Craig Venter Institute
  synonyms:
    - TIGR_CMR
    - TIGR_EGAD
  generic_urls:
    - http://cmr.jcvi.org/
  entity_types:
    - type_name: gene
      type_id: SO:0000704
      id_syntax: '[A-Z][A-Za-z0-9_]+(\.[0-9])?'
      url_syntax: http://cmr.jcvi.org/cgi-bin/CMR/shared/GenePage.cgi?locus=[example_id]
      example_id: JCVI_CMR:VCA0557
      example_url: http://cmr.jcvi.org/cgi-bin/CMR/shared/GenePage.cgi?locus=VCA0557
    - type_name: protein
      type_id: PR:000000001
      id_syntax: '[A-Z][A-Za-z0-9_]+(\.[0-9])?'
      url_syntax: http://cmr.jcvi.org/cgi-bin/CMR/shared/GenePage.cgi?locus=[example_id]
      example_id: JCVI_CMR:VCA0557
      example_url: http://cmr.jcvi.org/cgi-bin/CMR/shared/GenePage.cgi?locus=VCA0557
```

However, http://cmr.jcvi.org/ does not resolve
