### ISSUE TITLE
ASAP database no more?

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#949]
https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml#L94-L103

ASAP links are broken. Database gone?

Note that annotations to ASAP IDs are from PAMGO, see https://github.com/geneontology/go-site/blob/master/metadata/datasets/pamgo.yaml in the PAMGO_Ddadantii file.

I will contact the listed contact here

**Comment by cmungall** [comment]
From Eric Neeno-Eckwall at wisc:

The links you have to our database have changed, I found this in the db-xrefs.yaml file:

```
- database: ASAP
    name: A Systematic Annotation Package for Community Analysis of Genomes
    generic_urls:
    - https://asap.ahabs.wisc.edu/annotation/php/ASAP1.htm
    entity_types:
    -    type_name: gene
        type_id: SO:0000704
        url_syntax: https://asap.ahabs.wisc.edu/annotation/php/feature_info.php?FeatureID=[example_id]
        example_id: ASAP:ABE-0000008
        example_url: https://asap.ahabs.wisc.edu/annotation/php/feature_info.php?FeatureID=ABE-0000008
```

The URLs should be:
generic: https://asap.genetics.wisc.edu/asap/ASAP1.htm
syntax: https://asap.genetics.wisc.edu/asap/feature_info.php?FeatureID=[example_id]
example: https://asap.genetics.wisc.edu/asap/feature_info.php?FeatureID=ABF-0014586
