### ISSUE TITLE
GoRules: Yaml should have schema for example data each of a passing and a failing for the Go Rule

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#956]
In the GO Rules YAML, let's create specs for optional passing and failing exemplar data for that rule. There could be more than one example of each passing and failing and the data need not be GAF. 

Something like:
```
examples:
    pass:
        - format: rdf|gaf|gpad|etc?
          instance: "blah blah blah"
        - format: ...
    fail:
        - format: rdf|gaf|gpad|etc?
          instance: "blah blah blah"
```

Advantages to this is that it's still format agnostic. We can have an enum of allowed formats in the schema. What formats should be allowed here? Also, not sure if I like `instance` as the name here. Suggestions? The other advantage is that we can have any number of failing and passing examples in different formats. Each example should be expected to "pass" (all failing example entries should fail, all passing entries should pass the rule).

Tagging: @selewis @cmungall @kltm 
```
